# Generated by Django 3.1.4 on 2021-10-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20211019_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerbot',
            name='capacity',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='designerbot',
            name='cost',
            field=models.FloatField(blank=True, default=3470, null=True),
        ),
        migrations.AddField(
            model_name='designerbot',
            name='range',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='opsbot',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsbot',
            name='customers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsbot',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
