# Generated by Django 3.1.4 on 2021-10-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20211020_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerbot',
            name='last_iter_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='opsbot',
            name='last_iter_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
