# Generated by Django 3.1.4 on 2021-10-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_auto_20211020_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsbot',
            name='config',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
