# Generated by Django 3.0.2 on 2020-02-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200206_1411'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.DesignTeam'),
        ),
    ]
