# Generated by Django 3.0.2 on 2020-02-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0005_groupposition_primary'),
        ('chat', '0005_auto_20200214_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Session'),
        ),
    ]
