# Generated by Django 3.0.2 on 2020-02-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0005_groupposition_primary'),
        ('chat', '0006_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Session'),
        ),
    ]
