# Generated by Django 3.0.4 on 2020-03-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0009_auto_20200310_1958'),
        ('chat', '0007_auto_20200224_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Structure'),
        ),
    ]
