# Generated by Django 3.0.2 on 2020-02-13 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0006_auto_20200210_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use_ai', models.BooleanField()),
                ('status', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Experiment')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Market')),
                ('prior_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.DesignTeam')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Structure'),
        ),
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Role'),
        ),
        migrations.AddField(
            model_name='position',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Structure'),
        ),
        migrations.CreateModel(
            name='GroupPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Position')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Structure'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Study'),
        ),
    ]
