# Generated by Django 3.0.2 on 2020-02-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0002_study_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='prior_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Session'),
        ),
    ]
