# Generated by Django 3.0.2 on 2020-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0004_auto_20200214_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupposition',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
