# Generated by Django 3.0.2 on 2020-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0006_experiment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
