# Generated by Django 3.0.2 on 2020-02-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0007_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposition',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Session'),
        ),
    ]
