# Generated by Django 3.0.4 on 2020-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0008_userposition_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(default=4),
        ),
    ]
