# Generated by Django 3.0.6 on 2020-06-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0010_userchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2048)),
                ('link_type', models.IntegerField(null=True)),
                ('is_team', models.BooleanField(null=True)),
                ('ai', models.BooleanField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('first', models.BooleanField(null=True)),
                ('last', models.BooleanField(null=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Organization')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Position')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Role')),
            ],
        ),
    ]
