# Generated by Django 3.0.6 on 2020-06-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0011_customlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlinks',
            name='ai',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='first',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='is_team',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='last',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='link_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Organization'),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Position'),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Role'),
        ),
        migrations.AlterField(
            model_name='customlinks',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
