# Generated by Django 3.0.8 on 2020-08-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0013_customlinks_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Organization'),
        ),
    ]
