# Generated by Django 3.0.8 on 2020-09-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0014_structure_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Experiment'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.Exercise'),
        ),
    ]
