# Generated by Django 3.0.5 on 2020-11-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0020_auto_20200909_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time_interval', models.FloatField(default=1.0)),
                ('save_time_interval', models.FloatField(default=2.0)),
                ('quality_bias', models.FloatField(default=0.1)),
                ('self_bias', models.FloatField(default=0.1)),
                ('temperature', models.FloatField(default=0.2)),
                ('satisficing_factor', models.FloatField(default=0.2)),
                ('user_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.UserPosition')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_limit', models.FloatField(default=0.0)),
                ('upper_limit', models.FloatField(default=0.0)),
                ('digital_twin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.DigitalTwin')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pref_value', models.FloatField(default=0.0)),
                ('pref_type', models.IntegerField(default=0)),
                ('digital_twin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exper.DigitalTwin')),
            ],
        ),
    ]
