# Generated by Django 3.1.4 on 2021-02-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0021_digitaltwin_digitaltwinpreference_digitaltwinrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlinks',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.experiment'),
        ),
        migrations.AddField(
            model_name='customlinks',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.study'),
        ),
        migrations.CreateModel(
            name='StructureOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.organization')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.structure')),
            ],
        ),
    ]
