# Generated by Django 3.1.4 on 2021-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0023_session_use_process_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlinks',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
