# Generated by Django 3.1.4 on 2021-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0024_customlinks_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
