# Generated by Django 3.1.4 on 2021-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0025_session_is_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlinks',
            name='in_tutorial',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
