# Generated by Django 2.2.7 on 2019-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
            ],
        ),
    ]
