# Generated by Django 3.0.2 on 2020-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_datalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='payload',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
