# Generated by Django 3.0.2 on 2020-02-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='pathss',
            new_name='paths',
        ),
    ]
