# Generated by Django 3.0.2 on 2020-02-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200206_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='event',
            new_name='market',
        ),
    ]
