# Generated by Django 3.0.2 on 2020-02-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0004_auto_20200214_1254'),
        ('repo', '0006_auto_20200210_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Market'),
        ),
    ]
