# Generated by Django 3.0.2 on 2020-02-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0004_auto_20200214_1254'),
        ('repo', '0008_auto_20200217_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exper.Group'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exper.Session'),
        ),
    ]
