# Generated by Django 3.0.2 on 2020-02-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20200218_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PathCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='path',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='nodes',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.AddField(
            model_name='pathcustomer',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Path'),
        ),
        migrations.AddField(
            model_name='customerlist',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Scenario'),
        ),
    ]
