# Generated by Django 3.0.2 on 2020-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0010_auto_20200218_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='cusomters',
            field=models.ManyToManyField(through='repo.CustomerList', to='repo.Customer'),
        ),
    ]
