# Generated by Django 3.0.2 on 2020-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0012_auto_20200219_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='customers',
            field=models.ManyToManyField(related_name='customers', through='repo.CustomerScenario', to='repo.Customer'),
        ),
    ]
