# Generated by Django 3.0.2 on 2020-02-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_auto_20200219_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='customers',
        ),
    ]
