# Generated by Django 3.0.2 on 2020-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_remove_scenario_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='customers',
            field=models.ManyToManyField(related_name='customers', through='repo.CustomerScenario', to='repo.Customer'),
        ),
    ]
