# Generated by Django 3.0.2 on 2020-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0016_remove_scenario_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_exper',
            field=models.BooleanField(default=False),
        ),
    ]
