# Generated by Django 3.0.2 on 2020-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0018_auto_20200220_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathcustomer',
            name='stop',
            field=models.IntegerField(default=1),
        ),
    ]
