# Generated by Django 3.0.2 on 2020-02-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0019_pathcustomer_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathcustomer',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='repo.Path'),
        ),
    ]
