# Generated by Django 3.0.2 on 2020-02-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0020_auto_20200220_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='repo.Plan'),
        ),
    ]
