# Generated by Django 3.0.2 on 2020-02-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0007_organization'),
        ('repo', '0021_auto_20200220_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='designteam',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.DesignTeam'),
        ),
    ]
