# Generated by Django 3.0.2 on 2020-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0023_auto_20200306_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='type',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
