# Generated by Django 3.0.4 on 2020-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0024_datalog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='type',
            field=models.CharField(default='client', max_length=255),
        ),
    ]
