# Generated by Django 3.0.8 on 2020-09-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0027_auto_20200429_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
