# Generated by Django 3.0.5 on 2020-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0027_remove_profile_temp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_code',
            field=models.TextField(default=''),
        ),
    ]
