# Generated by Django 3.0.5 on 2020-05-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0028_profile_temp_code'),
        ('repo', '0027_auto_20200429_1430'),
    ]

    operations = [
    ]
