# Generated by Django 3.0.8 on 2020-09-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exper', '0015_auto_20200907_1752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0029_auto_20200909_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
