# Generated by Django 3.1.1 on 2020-09-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0029_merge_20200501_1418'),
        ('repo', '0030_experorg'),
    ]

    operations = [
    ]
