# Generated by Django 3.0.5 on 2020-11-30 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0031_merge_20200909_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='temp_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
