# Generated by Django 3.1.4 on 2021-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0032_auto_20201130_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerscenario',
            name='deviation',
            field=models.FloatField(default=0),
        ),
    ]
