# Generated by Django 3.1.4 on 2021-05-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0033_customerscenario_deviation'),
        ('repo', '0033_auto_20210319_1400'),
    ]

    operations = [
    ]
