# Generated by Django 3.1.4 on 2021-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0034_merge_20210517_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
