# Generated by Django 3.1.4 on 2021-09-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0035_vehicle_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
