# Generated by Django 3.1.4 on 2021-03-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exper', '0022_auto_20210221_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_type', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exper.session')),
            ],
        ),
    ]
