# Generated by Django 3.1.4 on 2021-03-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210319_1400'),
        ('exper', '0024_customlinks_active'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('session_timestamp', models.DateTimeField()),
                ('channelId', models.CharField(max_length=255, null=True)),
                ('message_type', models.CharField(max_length=255, null=True)),
                ('from_experimenter', models.BooleanField(default=False)),
                ('from_system', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=2048, null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.channel')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exper.position')),
            ],
        ),
    ]
