# Generated by Django 3.1.4 on 2021-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messagechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
