# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uavdesign.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uavdesign.proto',
  package='protodesign',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fuavdesign.proto\x12\x0bprotodesign\"\x1b\n\tUAVDesign\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"Y\n\x07Results\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05range\x18\x02 \x01(\x02\x12\x10\n\x08velocity\x18\x03 \x01(\x02\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x02\x12\x0f\n\x07payload\x18\x05 \x01(\x02\"U\n\nTrajResult\x12%\n\x07results\x18\x01 \x01(\x0b\x32\x14.protodesign.Results\x12 \n\x05trajs\x18\x02 \x03(\x0b\x32\x11.protodesign.Traj\"e\n\x04Traj\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\n\n\x02rx\x18\x05 \x01(\x02\x12\n\n\x02ry\x18\x06 \x01(\x02\x12\n\n\x02rz\x18\x07 \x01(\x02\x12\n\n\x02rw\x18\x08 \x01(\x02\x32\x9a\x01\n\x0c\x44\x65signAssess\x12\x43\n\x11GetUAVPerformance\x12\x16.protodesign.UAVDesign\x1a\x14.protodesign.Results\"\x00\x12\x45\n\x10GetUAVTrajectory\x12\x16.protodesign.UAVDesign\x1a\x17.protodesign.TrajResult\"\x00\x62\x06proto3'
)




_UAVDESIGN = _descriptor.Descriptor(
  name='UAVDesign',
  full_name='protodesign.UAVDesign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='protodesign.UAVDesign.config', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=59,
)


_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='protodesign.Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protodesign.Results.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range', full_name='protodesign.Results.range', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='protodesign.Results.velocity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='protodesign.Results.cost', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='protodesign.Results.payload', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=150,
)


_TRAJRESULT = _descriptor.Descriptor(
  name='TrajResult',
  full_name='protodesign.TrajResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='protodesign.TrajResult.results', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajs', full_name='protodesign.TrajResult.trajs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=237,
)


_TRAJ = _descriptor.Descriptor(
  name='Traj',
  full_name='protodesign.Traj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='protodesign.Traj.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='protodesign.Traj.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='protodesign.Traj.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='protodesign.Traj.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx', full_name='protodesign.Traj.rx', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ry', full_name='protodesign.Traj.ry', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rz', full_name='protodesign.Traj.rz', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rw', full_name='protodesign.Traj.rw', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=340,
)

_TRAJRESULT.fields_by_name['results'].message_type = _RESULTS
_TRAJRESULT.fields_by_name['trajs'].message_type = _TRAJ
DESCRIPTOR.message_types_by_name['UAVDesign'] = _UAVDESIGN
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
DESCRIPTOR.message_types_by_name['TrajResult'] = _TRAJRESULT
DESCRIPTOR.message_types_by_name['Traj'] = _TRAJ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UAVDesign = _reflection.GeneratedProtocolMessageType('UAVDesign', (_message.Message,), {
  'DESCRIPTOR' : _UAVDESIGN,
  '__module__' : 'uavdesign_pb2'
  # @@protoc_insertion_point(class_scope:protodesign.UAVDesign)
  })
_sym_db.RegisterMessage(UAVDesign)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'uavdesign_pb2'
  # @@protoc_insertion_point(class_scope:protodesign.Results)
  })
_sym_db.RegisterMessage(Results)

TrajResult = _reflection.GeneratedProtocolMessageType('TrajResult', (_message.Message,), {
  'DESCRIPTOR' : _TRAJRESULT,
  '__module__' : 'uavdesign_pb2'
  # @@protoc_insertion_point(class_scope:protodesign.TrajResult)
  })
_sym_db.RegisterMessage(TrajResult)

Traj = _reflection.GeneratedProtocolMessageType('Traj', (_message.Message,), {
  'DESCRIPTOR' : _TRAJ,
  '__module__' : 'uavdesign_pb2'
  # @@protoc_insertion_point(class_scope:protodesign.Traj)
  })
_sym_db.RegisterMessage(Traj)



_DESIGNASSESS = _descriptor.ServiceDescriptor(
  name='DesignAssess',
  full_name='protodesign.DesignAssess',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=343,
  serialized_end=497,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUAVPerformance',
    full_name='protodesign.DesignAssess.GetUAVPerformance',
    index=0,
    containing_service=None,
    input_type=_UAVDESIGN,
    output_type=_RESULTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUAVTrajectory',
    full_name='protodesign.DesignAssess.GetUAVTrajectory',
    index=1,
    containing_service=None,
    input_type=_UAVDESIGN,
    output_type=_TRAJRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DESIGNASSESS)

DESCRIPTOR.services_by_name['DesignAssess'] = _DESIGNASSESS

# @@protoc_insertion_point(module_scope)
